[workspace]
members = [
    "easy/solve-me-first",
    "easy/simple-array-sum",
    "easy/compare-the-triplets",

    "medium/magic-square-forming",
    "medium/climbing-the-leaderboard",
    "medium/extra-long-factorials",
    "medium/non-divisible-subset",
]

resolver = "2"
