[workspace]
members = [
    "easy/solve-me-first",
    "easy/simple-array-sum",
    "easy/compare-the-triplets",

    "medium/magic-square-forming",
    "medium/climbing-the-leaderboard",
]

resolver = "2"
